# Generated by Django 3.0.3 on 2020-02-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('Movies', 'movie'), ('Series', 'series'), ('Episodes', 'episodes')], max_length=100)),
                ('search_term', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmlookup.Search')),
            ],
        ),
    ]
