# Generated by Django 3.0.3 on 2020-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlookup', '0002_auto_20200225_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('ftype', models.CharField(choices=[('Movies', 'movie'), ('Series', 'series'), ('Episodes', 'episode')], max_length=100)),
                ('year', models.TextField(default='')),
                ('link', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='search_type',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AddField(
            model_name='search',
            name='results',
            field=models.ManyToManyField(to='filmlookup.Result'),
        ),
    ]
